// Generated by https://quicktype.io

export interface CreateResponse {
  createContent: CreateContent;
}

export interface CreateContent {
  content: Content[];
  version: string;
  description: string;
}

export interface Content {
  name: string;
  language: Language[];
}

export interface Language {
  lang: string;
  buttons: Button[];
  conditions: any[];
  text: string;
  regex: null | string;
}

export interface Button {
  text: string;
  event: string;
  data: null | string;
}
